### ISSUE TITLE
Crackling sound on the TS3 side

### ISSUE THREAD

**Issue by 3zet** [0xpr03/voice-bridge#1]
Hi, 

At first I want to write you made a really good job with that project! I never saw anything like this. 
I also have a problem. I already compile it and it runs just fine, when I speak from TS3 channel to the Discord one, on Discord everything is working. But in opposite direction (speak from Discord channel to TS3) there is terrible distortion like the sound is on and off constantly many times per second. Also out traffic on TS3 shows really huge packet loss and already checked that, that's not the hosting machine or its equipment. I found the music bot which is sending voice from Discord to TS3 works perfectly fine, packet loss starts when anybody starts talking from Discord to TS3. Both DS and TS3 servers are on seperate hostings, voice-bridge is running on my local machine which acts as server, running 24/7 (Mint 20.1). 

Now I can't catch it for the screenshot but packet loss jumps 
up and down quickly; from 3 to 5%, one time had over 70% packet loss. And its only single way, that's the weirdest thing. 
![screenshot-298](https://user-images.githubusercontent.com/69508064/124401387-22a79780-dd21-11eb-839f-d87df6cb5136.png)
I hope you will be able to track what was happened because the sound issue sounds like audio buffer problem. 

Thanks in advance.

**Comment by 0xpr03** [comment]
The discord -> ts pipeline currently has no correct jitter buffer and requires a kinda realtime runtime in regards to CPU usage. Interestingly it's the complete opposite for me, as voice is no problem, but audio bots in discord will give up to 30% package loss in teamspeak.

**Comment by 3zet** [comment]
Will be glad to test it!
Thanks for your response.

**Comment by 0xpr03** [comment]
I've had a go at this the last two days and am still fixing issues with the jitter buffer where packages can't be decoded, just so you know

**Comment by 0xpr03** [comment]
Ok at first implementation can be found on the branch linked.

**Comment by 0xpr03** [comment]
Something probably missing is a package reordering currently, but this should already improve the issue a lot.

**Comment by 3zet** [comment]
Looks pretty nice, I will try it very soon!

**Comment by 3zet** [comment]
Oh my, it works well enough to be used on my friends Discord server. Very good job!

**Comment by 0xpr03** [comment]
Ah nice, then I'll merge that. I was thinking about possible features for this. For example if we'd should move the ~join stuff towards the coming `/` bot commands in discord. Or auto detect people in a voice channel, name changes etc. I mean, we could add a webinterface for stuff like volume changes.
