### ISSUE TITLE
TS3Username Change?

### ISSUE THREAD

**Issue by Mustang0021** [0xpr03/voice-bridge#2]
Is it possible to change the TeamSpeak name?

**Comment by 3zet** [comment]
Not in easy way - You need to find Teamspeak config lib in rust dependencies and there edit the username before compilation.

**Comment by 0xpr03** [comment]
Currently not, do you just want a config option ?

**Comment by 0xpr03** [comment]
> 
> 
> Not in easy way - You need to find Teamspeak config lib in rust dependencies and there edit the username before compilation.

Please don't do that 😅 You'll have fun times rebuilding and validating your dependency cache if something goes wrong.

**Comment by Mustang0021** [comment]
Yes, it would be nice if it would be possible to simply enter the nickname in a file.

**Comment by 0xpr03** [comment]
I added the name,channel-id,channel-name and password options. See new credentials examples.
