### ISSUE TITLE
Buffer not keeping up after some time

### ISSUE THREAD

**Issue by 3zet** [0xpr03/voice-bridge#3]
I forgot to put this, after some 30 minutes to one hour of continues usage sound heard on teamspeak starts to crackling. Also discord music bots are crackling on teamspeak but I think is the volume issue.

**Comment by 0xpr03** [comment]
Are there any log outputs for that, like warnings regarding buffers ? You could try running a debug build with `cargo run` as release optimizes out some log entries and uses a higher default log-level.

**Comment by 0xpr03** [comment]
I also pushed a fairly large change with the songbird 0.2 migration and couldn't reproduce persistent errors when streaming music from/to teamspeak/discord over 2 hours. So your observations might be different now.

**Comment by 3zet** [comment]
Yeah, is definitely much better with new build. I can close this issue now
