### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by KaratekHD** [0xpr03/voice-bridge#5]
Hi,
I am planning  to deploy this project and ran into some issues that I think could be caused by the program running out of memory. Could you please provide some information about how much memory is needed to run this?
Thanks in advance

~ Jens

**Comment by 0xpr03** [comment]
uhm, the program doesn't really need much, you're not trying to run that on a potato, are you ?

**Comment by 0xpr03** [comment]
I'm just testing it just to give you a number.
While doing so I realized: You aren't trying to compile this in release mode on a rasberry pi, are you ? Because that would explain the issue.

**Comment by 0xpr03** [comment]
Runtime requirement it 3,7MB of RAM.

You may want to compile this on a PC though. If required I can setup cross-compilation so some ARM binaries are pushed to the release page.

**Comment by 0xpr03** [comment]
For CPU, well you don't want cpu hangs because your connection and cpu load dictate the quality of the transmission

**Comment by KaratekHD** [comment]
Thank you for the details!
The machine I'm trying to compile this on is a VPS with 4GB of RAM, however compilation fails. I then built it on my desktop PC, which has 32GB of RAM and 6 cores, and everything went well. I transfered the build over to the VPS, but couldn't run it: `Illegal instruction (core dumped)` (Both machines are the same architecture and both are running  openSUSE Tumbleweed). I'm currently working  on a Dockerfile for this, so that I can build a container and transfer that to the VPS. I can do a PR with this once I've finished it if you're interested.

**Comment by 0xpr03** [comment]
> Illegal instruction (core dumped

Please remove this line https://github.com/0xpr03/voice-bridge/blob/99dc2c34480b65c4762d75b70375989f5c6fca7a/.cargo/config.toml#L2

And recompile. Otherwise your VPS has to have the exact same CPU as you do, as its optimized for the CPU architecture you're compiling with.

**Comment by KaratekHD** [comment]
Thank you for this detailed answer, this helped me a lot. After removing that line I could run the Bridge with no issues, so there is no need for me to do containers anymore. 
I am really amazed by how well the bridge works, thank you so much for all the work you did, this finally enables me to participate in calls with people unwilling to install TeamSpeak. 
If I find some time in the future, I will package this for openSUSE, because this really is amazing! Keep up your work!

**Comment by 0xpr03** [comment]
Glad it works.
Note though that this is still an MVP. I've not added things like recovery from being kicked from teamspeak or not being able to join etc.
